apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: amitdusane/order-service:${IMAGE_TAG}
          env:
            - name: IMAGE_TAG
              value: "__IMAGE_TAG__" # Placeholder, replaced by GitHub Actions
          ports:
            - containerPort: 8082
          imagePullPolicy: Always

