apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: amitdusane/order-service:__IMAGE_TAG__
          ports:
            - containerPort: 8082
          imagePullPolicy: Always

